/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentazione.eventi;
import data.Eventi;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.eventi.ModificaEventoController;

/**
 *
 * @author Dastler
 */
public class ModificaEvento extends javax.swing.JFrame {
    Eventi daModificare;
    javax.swing.JFrame frame;
    Date date;
    SimpleDateFormat sdf;
    ModificaEventoController controller; 
    /**
     * Creates new form ModificaEvento2
     */
    public ModificaEvento(Eventi e,ModificaEventoController controller,javax.swing.JFrame ricercaFrame ) throws ParseException {
        daModificare=e;
        frame=ricercaFrame;
        this.controller=controller;
        sdf=new SimpleDateFormat("yyyy-MM-d");
        date=sdf.parse(daModificare.getData());
        sdf.applyPattern("d/mm/yyyy");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        descrizioneTextField = new javax.swing.JTextField();
        descrizioneLabel = new javax.swing.JLabel();
        cittaLabel = new javax.swing.JLabel();
        cittaComboBox = new javax.swing.JComboBox<>();
        dataChooser = new com.toedter.calendar.JDateChooser();
        dataLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        categoriaComboBox = new javax.swing.JComboBox<>();
        prezzoTextField = new javax.swing.JTextField();
        prezzoLabel = new javax.swing.JLabel();
        bigliettiLabel = new javax.swing.JLabel();
        bigliettiSpinField = new com.toedter.components.JSpinField();
        addImgLabel = new javax.swing.JLabel();
        indietroButton = new javax.swing.JButton();
        salvaButton = new javax.swing.JButton();
        imgTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setPreferredSize(new java.awt.Dimension(470, 520));
        setResizable(false);

        nomeLabel.setText("Nome evento : ");

        nomeTextField.setText(daModificare.getNome());
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeTextFieldKeyReleased(evt);
            }
        });

        descrizioneTextField.setText(daModificare.getDescr());
        descrizioneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descrizioneTextFieldActionPerformed(evt);
            }
        });
        descrizioneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descrizioneTextFieldKeyReleased(evt);
            }
        });

        descrizioneLabel.setText("Descrizione : ");

        cittaLabel.setText("Città : ");

        cittaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aosta", "Verbania", "Biella", "Novara", "Torino", "Vercelli", "Asti", "Alessandria", "Cuneo", "Savona", "Imperia", "La Spezia", "Genova", "Sondrio", "Como", "Lecco", "Varese", "Bergamo", "Milano", "Brescia", "Pavia", "Lodi", "Cremona", "Mantova", "Trento", "Bolzano", "Belluno", "Vicenza", "Treviso", "Verona", "Venezia", "Padova", "Rovigo", "Pordenone", "Gorizia", "Udine", "Trieste", "Piacenza-ParmaReggio", "Emilia", "Modena", "Bologna", "Ferrara", "Ravenna", "Forlì", "Rimini", "Massa", "Lucca", "Pistoia", "Prato", "Firenze", "Pisa", "Arezzo", "Livorno", "Siena", "Grosseto", "Perugia", "Terni", "Pesaro", "Ancona", "Macerata", "Ascoli", "Piceno", "Viterbo", "Rieti", "Roma", "Latina", "Frosinone", "Teramo", "Pescara", "L’Aquila", "Chieti", "Isernia", "Campobasso", "Avellino", "Napoli", "Benevento", "Caserta", "Salerno", "Foggia", "Bari", "Taranto", "Brindisi", "Potenza", "Matera", "Cosenza", "Crotone", "Catanzaro", "Vibo Valentia", "Reggio Calabria", "Lecce", "Trapani", "Palermo", "Messina", "Caltanissetta", "Agrigento", "Enna", "Catania", "Ragusa", "Siracusa", "Olbia Tempio", "Sassari", "Nuoro", "Oristano", "Ogliastra", "Medio Campidano", "Cagliari", "Carbonia Iglesias" }));
        cittaComboBox.setSelectedItem(daModificare.getCitta());

        dataChooser.setDateFormatString("d/MM/yyyy");
        dataChooser.setDate(date);

        dataLabel.setText("Data :");

        categoriaLabel.setText("Categoria :");

        categoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cinema", "Spettacolo", "Conferenza", "Musica","Sport" }));
        categoriaComboBox.setSelectedItem(daModificare.getCategoria());
        categoriaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaComboBoxActionPerformed(evt);
            }
        });

        prezzoTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        prezzoTextField.setText(Double.toString(daModificare.getPrezzo()));
        prezzoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prezzoTextFieldKeyReleased(evt);
            }
        });

        prezzoLabel.setText("Prezzo :");

        bigliettiLabel.setText("N° biglietti disponibili :");

        bigliettiSpinField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bigliettiSpinFieldPropertyChange(evt);
            }
        });

        addImgLabel.setText("Aggiungi immagini :");

        indietroButton.setText("Indietro");
        indietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroButtonActionPerformed(evt);
            }
        });

        salvaButton.setText("Salva");
        salvaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaButtonActionPerformed(evt);
            }
        });

        imgTextField.setText(daModificare.getNomeImmagine());
        imgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("es. 23.7");
        jLabel1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Modifica evento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indietroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvaButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descrizioneLabel)
                            .addComponent(cittaLabel)
                            .addComponent(dataLabel)
                            .addComponent(categoriaLabel)
                            .addComponent(addImgLabel)
                            .addComponent(nomeLabel)
                            .addComponent(bigliettiLabel)
                            .addComponent(prezzoLabel))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bigliettiSpinField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(prezzoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descrizioneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cittaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(categoriaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descrizioneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cittaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cittaLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomeLabel)
                        .addGap(31, 31, 31)
                        .addComponent(descrizioneLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dataChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(dataLabel)
                        .addGap(18, 18, 18)
                        .addComponent(categoriaLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prezzoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prezzoLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(bigliettiLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bigliettiSpinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(addImgLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indietroButton)
                    .addComponent(salvaButton))
                .addContainerGap())
        );

        bigliettiSpinField.setValue(daModificare.getBiglietti());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextFieldKeyReleased
        // TODO add your handling code here:
        if(areFull()) salvaButton.setEnabled(true);
        else salvaButton.setEnabled(false);
    }//GEN-LAST:event_nomeTextFieldKeyReleased

    private void descrizioneTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descrizioneTextFieldKeyReleased
        // TODO add your handling code here:
        if(areFull()) salvaButton.setEnabled(true);
        else salvaButton.setEnabled(false);
    }//GEN-LAST:event_descrizioneTextFieldKeyReleased

    private void prezzoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prezzoTextFieldKeyReleased
        // TODO add your handling code here:
        if(areFull() && inputTextControl(prezzoTextField.getText())){
            salvaButton.setEnabled(true);
            jLabel1.setEnabled(false);
        }
        else{
            salvaButton.setEnabled(false);
            jLabel1.setEnabled(true);
        }
    }//GEN-LAST:event_prezzoTextFieldKeyReleased

    private void bigliettiSpinFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bigliettiSpinFieldPropertyChange
        // TODO add your handling code here:
        if(areFull()) salvaButton.setEnabled(true);
        else salvaButton.setEnabled(false);
    }//GEN-LAST:event_bigliettiSpinFieldPropertyChange

    private void indietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroButtonActionPerformed
        // TODO add your handling code here:
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_indietroButtonActionPerformed

    private void salvaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaButtonActionPerformed
        // TODO add your handling code here:
        Date o = dataChooser.getDate();
        String x = String.format("%1$td/%1$tm/%1$tY",o);
        frame.dispose();
        try {
            if(controller.eseguiModifica(nomeTextField.getText(),daModificare.getCodice(),descrizioneTextField.getText(),(String)cittaComboBox.getSelectedItem(),x,(String)categoriaComboBox.getSelectedItem(),new Float(prezzoTextField.getText()),bigliettiSpinField.getValue(),imgTextField.getText())){
                new SuccessoModifica().setVisible(true);
                this.dispose();
            }
            else{
                new ErroreModifica().setVisible(true);
                this.dispose();
            }
        } catch (IOException ex) {
            Logger.getLogger(ModificaEvento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvaButtonActionPerformed

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void descrizioneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descrizioneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descrizioneTextFieldActionPerformed

    private void imgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgTextFieldActionPerformed

    private void categoriaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ModificaEvento(null,null,null).setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(ModificaEvento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addImgLabel;
    private javax.swing.JLabel bigliettiLabel;
    private com.toedter.components.JSpinField bigliettiSpinField;
    private javax.swing.JComboBox<String> categoriaComboBox;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JComboBox<String> cittaComboBox;
    private javax.swing.JLabel cittaLabel;
    private com.toedter.calendar.JDateChooser dataChooser;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel descrizioneLabel;
    private javax.swing.JTextField descrizioneTextField;
    private javax.swing.JTextField imgTextField;
    private javax.swing.JButton indietroButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel prezzoLabel;
    private javax.swing.JTextField prezzoTextField;
    private javax.swing.JButton salvaButton;
    // End of variables declaration//GEN-END:variables
    private boolean areFull(){
        return !nomeTextField.getText().isEmpty() && !descrizioneTextField.getText().isEmpty()&& !prezzoTextField.getText().isEmpty() && bigliettiSpinField.getValue()>0 ; 
    }
    private boolean inputTextControl(String text1){
        return text1.matches("^[0-9]+[.]+[0-9]*" );
    
    }
}
